### PR TITLE
Add Catalan and Spanish translations.

### PR DESCRIPTION
**Pull request by pataquets**

### CODE REVIEW

**Comment by pataquets** [comment]
@Miskerest : Travis is failing, but looks like it's not related to translations.

**Comment by Miskerest** [comment]
@pataquets  yes, I haven't gotten Travis working. I'll push this out to the Play Store soon. Thanks for the contribution, this looks great.

**Comment by Miskerest** [comment]
@pataquets I've just rolled out the update to the Play Store. Please try it out and tell me if there's any issues! Thanks again.

**Comment by pataquets** [comment]
You're welcome @Miskerest. Happy to give back.
I've finally had a chance to test them.
Applies to both languages:
- File and text upper tab titles are not translated (uppercase?)
- Same for 'select' file button
- Same for hashes match toast

Looks like they are not in the base English strings file.

**Comment by Miskerest** [comment]
Hi @pataquets,

I think I've fixed all these. I tested in each locale, and they all seemed to appear correctly. Next up is fixing some minor memory leaks, once I get the free time :)

**Pull request merged**
