### PR TITLE
Create hashers and the hasher factory

### PR DESCRIPTION
**Pull request by spargonaut**
Let me know what you think of this.

I've extracted the switch statement in the HashRunnable into a factory class to reduce some duplicate code and implement the [strategy pattern](https://en.wikipedia.org/wiki/Strategy_pattern).

I've tweaked the implementation a little bit in that each implementation of the hashing takes a string as input instead of an input stream since it was easier to test.  Unfortunately, that has led to some wonkyness, but I think its worth it in the long run because it'll eventually shake out.

Let me know of any questions you might have, I'm happy to talk things through.

### CODE REVIEW

**Comment by Miskerest** [comment]
Hey @spargonaut, this looks great. Did you build/test these changes? I plan on doing so when I get the time.

**Comment by spargonaut** [comment]
I tested all of the algorithms, but only on strings really.  When I tested it on an iso, it ran out of memory, hence the refactorings and updates (sorry about that).  I test drove the implementations until I had something I could replace that/those big switch statements with.  This current implementation passes for MD5, SHA1, SHA256, SHA512, but i'm not sure where to get some known good values of the other algorithms (SHA384, CRC32, Adler32) to test some files.

Do you have a file and their hashes with the assorted algorithms I could use for manual testing?

I expect things to pass at this point, but without test data, I can't be 100% certain.  Let me know what you observe, and I'll make changes as needed.

**Comment by Miskerest** [comment]
Alrighty, I'll test them against the old implementation and see how it goes!

**Comment by Miskerest** [comment]
Everything seems to be hashing to the correct values. I've been using this image for testing:
test image 
Here are some correct values:

* 79C66589B8178CF9F0F5B00EEE1C91D4 - MD5
* A6555B126EFD1AACFBE3A9E80AE4535222ED3FC66B3AF6A98EDBE8DD406DE1FF - SHA256
* 1B67F32E9DD83707BFDB6D17C1E4A0DB643567B2702201D358E587D6FEB368F295BBDF6AF7B90AC23815C3876014BB66 - SHA384
* E21271AB - CRC32b
* E9B1CCBB - Adler32

**Comment by Miskerest** [comment]
I wonder if it's worthwhile to include some `hashers` tests using that image?

**Comment by spargonaut** [comment]
image:
the link you provided for the image goes to ```https://hiset.ets.org/take/``` as opposed to an actual image.  I have the feeling that's not what you intended.

Including an image in the automated tests:
I think including a test against an image can be a good idea for a functional test (espresso), but IMO, I think it would make unit tests a bit too resource intensive and fragile.  I generally don't let my unit tests do any disk I/O for a host of different reasons.

Sorry I'm slacking on those espresso tests, i'm kind of working on a number of side projects, hasher only being one of them.

manual tests:
I think it might not be a bad idea to create some sort of testing.md document that explains your testing strategy, and include any test files and values in a support directory or something so that contributors can use to verify their work.  That might be a discussion for a different thread though.

**Comment by Miskerest** [comment]
Oops, darn Google and their removal of image links from searches. I just attached the image above. No worries about the espresso tests, I've been slammed with schoolwork recently. Will make note of the testing.md idea. Merging!

**Pull request closed without merging**
